# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      # Specify service dependencies here if necessary
 
    working_directory: ~/Nightwatch-circleci-selenium
    steps:
      - checkout
      
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export LT_USERNAME="anju003@ymail.com"' >> $BASH_ENV

      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export LT_ACCESS_KEY="jZkan1f4AinKYV6e4ABLLCim37omYgiEjmgK4ePpwInnu3pmmh"' >> $BASH_ENV

      - run: # test what branch we're on.
          name: "Here is the LT_Username : "
          command: echo ${LT_USERNAME}
          
      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found

      - run: npm install
      - run: node_modules/.bin/nightwatch -e chrome
